export interface IActualNews {
    "section_id"?: Number,
    "name"?: String,
    "preview_text"?: String,
    "content_type"?: String,
    "date_creation"?: String,
    "active"?: Boolean,
    "id"?: Number,
    "content_text"?: String,
    "date_publiction"?: String,
    "indirect_data"?: {
        "ID"?: String,
        "PREVIEW_PICTURE"?: string,
        "DETAIL_PICTURE"?: string,
        "IBLOCK_ID"?: String,
        "NAME"?: String,
        "CREATED_BY"?: String,
        "BP_PUBLISHED"?: String,
        "DATE_CREATE"?: String,
        "ACTIVE_FROM_X"?: String,
        "ACTIVE_FROM"?: String,
        "PROPERTY_1066"?: String[],
        "PROPERTY_1116"?: String[],
        "PROPERTY_284"?: String[],
        "PROPERTY_285"?: String[],
        "PROPERTY_289"?: String[],
        "PROPERTY_290"?: String[],
        "PROPERTY_291"?:
        {
            "TYPE"?: String,
            "TEXT"?: String,
        }[],
        "PROPERTY_292"?: String[],
        "PROPERTY_293"?: String[],
        "PROPERTY_294"?: String[],
        "PROPERTY_295"?: String[],
        "PROPERTY_296"?: String[],
        "reactions"?: {
            "likes"?: string,
            "dislikes"?: string,
        },
    },
    "images"?: [],
    "embedVideos"?: [],
    "nativeVideos"?: [],
    "reactions"?: {
        "likes"?: {
            "mine"?: boolean,
            "count"?: number,
        },
        "views"?: string,
    },
    "videos"?: [],
    "tags"?: [],
    "documents"?: {
        link: string,
        name: string,
    }
}