# # ─── Белый список origin'ов для CORS (в контексте http) ───
# map $http_origin $cors_origin {
#     default "";
#     "http://localhost:5173"              $http_origin;
#     "http://agrofconf.emk.org.ru"        $http_origin;
#     "https://agrofconf.emk.org.ru"       $http_origin;
#     "https://intranet.emk.org.ru"        $http_origin;
# }

server {
    listen 80;
    server_name ${NGINX_HOST};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ${NGINX_HOST};

    ssl_certificate /etc/nginx/conf.d/ssl/intranet.emk.ru.crt;
    ssl_certificate_key /etc/nginx/conf.d/ssl/intranet.emk.ru.key;

    ssl_protocols TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    client_max_body_size 1024M;
    etag off;

    underscores_in_headers on;
    error_page 404 502 503 504 /50x.html;

    location = /50x.html {
        root /etc/nginx/conf.d/errors;
        internal;
        sub_filter 'src="./cat502.jpg"' 'src="/err_static/cat502.jpg"';
        sub_filter_once on;
    }

    location /err_static/ {
        alias /etc/nginx/conf.d/errors/;
        expires 1h;
    }

    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_read_timeout     1200;
        proxy_connect_timeout  600;
        proxy_redirect         off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        proxy_cache off;
    }
    #$cors_origin always;
    location /api/ {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin'      'http://localhost:5173'; 
            add_header 'Access-Control-Allow-Methods'     'GET, POST, PUT, DELETE, PATCH, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers'     'Content-Type, Accept, Authorization, Location, Allow, Content-Disposition, Sec-Fetch-Dest, Access-Control-Allow-Credentials, session_id' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Max-Age'           86400 always;
            add_header 'Content-Length'                   0 always;
            return 204;
        }

        add_header 'Access-Control-Allow-Origin'      '$http_origin' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods'     'GET, POST, PUT, DELETE, PATCH, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers'     'Authorization, Content-Type, X-Requested-With, Accept, session_id' always;

        proxy_pass http://fastapi:8000;
        proxy_http_version 1.1;
        proxy_read_timeout 1200;
        proxy_connect_timeout 600;
        proxy_redirect off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header Connection "";

        proxy_cache off;
    }

    # location /ws/ {
    #     proxy_pass http://fastapi:8000;
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "Upgrade";
    # }
}